include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Desabilitar regras muito restritivas para estudo
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    eol_at_end_of_file: false
    directives_ordering: false
    avoid_redundant_argument_values: false

    # Manter boas práticas essenciais
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

  language:
    strict-casts: true
    strict-raw-types: true
