// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_widgets/test/unit/data/repositories/widgets_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_widgets/data/datasources/local/widgets_local_datasource.dart'
    as _i2;
import 'package:flutter_widgets/data/models/flutter_widget_model.dart' as _i5;
import 'package:flutter_widgets/data/models/widget_category_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WidgetsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWidgetsLocalDataSource extends _i1.Mock
    implements _i2.WidgetsLocalDataSource {
  MockWidgetsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.WidgetCategoryModel>> getCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i3.Future<List<_i4.WidgetCategoryModel>>.value(
            <_i4.WidgetCategoryModel>[]),
      ) as _i3.Future<List<_i4.WidgetCategoryModel>>);

  @override
  _i3.Future<List<_i5.FlutterWidgetModel>> getWidgets() => (super.noSuchMethod(
        Invocation.method(
          #getWidgets,
          [],
        ),
        returnValue: _i3.Future<List<_i5.FlutterWidgetModel>>.value(
            <_i5.FlutterWidgetModel>[]),
      ) as _i3.Future<List<_i5.FlutterWidgetModel>>);

  @override
  _i3.Future<List<_i5.FlutterWidgetModel>> getWidgetsByCategory(
          String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWidgetsByCategory,
          [categoryId],
        ),
        returnValue: _i3.Future<List<_i5.FlutterWidgetModel>>.value(
            <_i5.FlutterWidgetModel>[]),
      ) as _i3.Future<List<_i5.FlutterWidgetModel>>);

  @override
  _i3.Future<_i5.FlutterWidgetModel?> getWidgetById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWidgetById,
          [id],
        ),
        returnValue: _i3.Future<_i5.FlutterWidgetModel?>.value(),
      ) as _i3.Future<_i5.FlutterWidgetModel?>);

  @override
  _i3.Future<List<String>> getFavoriteIds() => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteIds,
          [],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<void> toggleFavorite(String? widgetId) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [widgetId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isFavorite(String? widgetId) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [widgetId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
